# - name: Install Open-shift 
#   pip:
#     name: openshift
   
- name: Provision Deployment object 
  k8s:
    state: present
    src: C:\Users\myvm\terraform-ansible-k8s project\k8s\deployement.yaml

- name: Provision LoadBalancer service object 
  k8s:
    state: present
    src: C:\Users\myvm\terraform-ansible-k8s project\k8s\service.yaml